In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data
import yfinance as yf
from datetime import datetime

In [2]:
yf.pdr_override()
tickers = ['TSLA'] # Aquí ponen los tickers de las empresas/índices de su interes

start_date = datetime(2003, 5, 16)  # Data di inizio
end_date = datetime(2023, 5, 14)
dati = data.get_data_yahoo(tickers, start_date, end_date)

[*********************100%***********************]  1 of 1 completed

In [3]:
#dati.reset_index().to_csv('TSLA.csv')

In [4]:
tickers = ['TSLA', 'AAPL', 'KO', 'MCD']

In [6]:
matrice_prezzi = pd.DataFrame()
for t in tickers:
    matrice_prezzi[t] = data.get_data_yahoo(t, start_date, end_date)['Adj Close']

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [7]:
matrice_prezzi

                  TSLA        AAPL         KO         MCD
Date
2010-06-29    1.592667    7.755360  16.594778   45.765087
2010-06-30    1.588667    7.614889  16.525522   45.358795
2010-07-01    1.464000    7.522552  16.495859   45.937225
2010-07-02    1.280000    7.475930  16.502449   45.544720
2010-07-06    1.074000    7.527096  16.627745   45.524071
...                ...         ...        ...         ...
2023-05-08  171.789993  172.799042  62.440350  291.796814
2023-05-09  169.149994  171.076035  61.922619  291.767334
2023-05-10  168.539993  172.858795  62.030071  291.678802
2023-05-11  172.080002  173.048050  62.381737  289.928162
2023-05-12  167.979996  172.110550  62.625954  291.255890

[3241 rows x 4 columns]

In [8]:
import yfinance as yf
import pandas as pd

In [9]:
from yahooquery import Ticker

aapl = Ticker('msft')

aapl.summary_detail

{'msft': 'Invalid Cookie'}

In [12]:
from yahooquery import Ticker

symbols = [ 'aapl', 'amzn', 'nflx', 'goog']

faang = Ticker(symbols)

faang.summary_detail

{'aapl': 'Invalid Cookie',
 'amzn': 'Invalid Cookie',
 'nflx': 'Invalid Cookie',
 'goog': 'Invalid Cookie'}

## Stato Patrimoniale

In [13]:
aapl = Ticker('msft')
balance=aapl.balance_sheet()
balance

,asOfDate,periodType,currencyCode,AccountsPayable,AccountsReceivable,AccumulatedDepreciation,AllowanceForDoubtfulAccountsReceivable,BuildingsAndImprovements,CapitalLeaseObligations,CapitalStock,...,TotalCapitalization,TotalDebt,TotalEquityGrossMinorityInterest,TotalLiabilitiesNetMinorityInterest,TotalNonCurrentAssets,TotalNonCurrentLiabilitiesNetMinorityInterest,TotalTaxPayable,TradeandOtherPayablesNonCurrent,WorkInProcess,WorkingCapital
symbol,,,,,,,,,,,,,,,,,,,,,
msft,2020-06-30,12M,USD,1.253000e+10,3.201100e+10,-4.319700e+10,-788000000.0,3.399500e+10,7.671000e+09,8.055200e+10,...,1.778820e+11,7.099800e+10,1.183040e+11,1.830070e+11,1.193960e+11,1.106970e+11,2.130000e+09,2.943200e+10,83000000.0,1.096050e+11
msft,2021-06-30,12M,USD,1.516300e+10,3.804300e+10,-5.135100e+10,-751000000.0,4.392800e+10,9.629000e+09,8.311100e+10,...,1.920620e+11,6.777500e+10,1.419880e+11,1.917910e+11,1.493730e+11,1.031340e+11,2.174000e+09,2.719000e+10,79000000.0,9.574900e+10
msft,2022-06-30,12M,USD,1.900000e+10,4.426100e+10,-5.966000e+10,-633000000.0,5.501400e+10,1.148900e+10,8.693900e+10,...,2.135740e+11,6.127000e+10,1.665420e+11,1.982980e+11,1.951560e+11,1.032160e+11,4.067000e+09,2.606900e+10,82000000.0,7.460200e+10
msft,2023-06-30,12M,USD,1.809500e+10,4.868800e+10,-6.825100e+10,-650000000.0,6.846500e+10,1.272800e+10,9.371800e+10,...,2.482130e+11,5.996500e+10,2.062230e+11,2.057530e+11,2.277190e+11,1.016040e+11,4.152000e+09,2.556000e+10,23000000.0,8.010800e+10

In [14]:
balance.columns

Index(['asOfDate', 'periodType', 'currencyCode', 'AccountsPayable',
       'AccountsReceivable', 'AccumulatedDepreciation',
       'AllowanceForDoubtfulAccountsReceivable', 'BuildingsAndImprovements',
       'CapitalLeaseObligations', 'CapitalStock', 'CashAndCashEquivalents',
       'CashCashEquivalentsAndShortTermInvestments', 'CashEquivalents',
       'CashFinancial', 'CommonStock', 'CommonStockEquity', 'CurrentAssets',
       'CurrentDebt', 'CurrentDebtAndCapitalLeaseObligation',
       'CurrentDeferredLiabilities', 'CurrentDeferredRevenue',
       'CurrentLiabilities', 'FinishedGoods',
       'GainsLossesNotAffectingRetainedEarnings', 'Goodwill',
       'GoodwillAndOtherIntangibleAssets', 'GrossAccountsReceivable',
       'GrossPPE', 'HedgingAssetsCurrent', 'IncomeTaxPayable', 'Inventory',
       'InvestedCapital', 'InvestmentsAndAdvances', 'LandAndImprovements',
       'Leases', 'LongTermCapitalLeaseObligation', 'LongTermDebt',
       'LongTermDebtAndCapitalLeaseObligation', 'LongTermEquityInvestment',
       'MachineryFurnitureEquipment', 'NetDebt', 'NetPPE', 'NetTangibleAssets',
       'NonCurrentDeferredLiabilities', 'NonCurrentDeferredRevenue',
       'NonCurrentDeferredTaxesLiabilities', 'OrdinarySharesNumber',
       'OtherCurrentAssets', 'OtherCurrentLiabilities',
       'OtherEquityAdjustments', 'OtherIntangibleAssets',
       'OtherNonCurrentAssets', 'OtherNonCurrentLiabilities',
       'OtherProperties', 'OtherShortTermInvestments', 'Payables',
       'PayablesAndAccruedExpenses',
       'PensionandOtherPostRetirementBenefitPlansCurrent', 'Properties',
       'RawMaterials', 'Receivables', 'RetainedEarnings', 'ShareIssued',
       'StockholdersEquity', 'TangibleBookValue', 'TotalAssets',
       'TotalCapitalization', 'TotalDebt', 'TotalEquityGrossMinorityInterest',
       'TotalLiabilitiesNetMinorityInterest', 'TotalNonCurrentAssets',
       'TotalNonCurrentLiabilitiesNetMinorityInterest', 'TotalTaxPayable',
       'TradeandOtherPayablesNonCurrent', 'WorkInProcess', 'WorkingCapital'],
      dtype='object')

## Cash flow

In [15]:
aapl = Ticker('msft')
cash_flow=aapl.cash_flow(trailing=False)
cash_flow

,asOfDate,periodType,currencyCode,BeginningCashPosition,CapitalExpenditure,CashDividendsPaid,CashFlowFromContinuingFinancingActivities,CashFlowFromContinuingInvestingActivities,CashFlowFromContinuingOperatingActivities,ChangeInAccountPayable,...,NetShortTermDebtIssuance,OperatingCashFlow,OperatingGainsLosses,PurchaseOfBusiness,PurchaseOfInvestment,PurchaseOfPPE,RepaymentOfDebt,RepurchaseOfCapitalStock,SaleOfInvestment,StockBasedCompensation
symbol,,,,,,,,,,,,,,,,,,,,,
msft,2020-06-30,12M,USD,1.135600e+10,-1.544100e+10,-1.513700e+10,-4.603100e+10,-1.222300e+10,6.067500e+10,3.018000e+09,...,0.0,6.067500e+10,-2.190000e+08,-2.521000e+09,-7.719000e+10,-1.544100e+10,-5.518000e+09,-2.296800e+10,8.417000e+10,5.289000e+09
msft,2021-06-30,12M,USD,1.357600e+10,-2.062200e+10,-1.652100e+10,-4.848600e+10,-2.757700e+10,7.674000e+10,2.798000e+09,...,NaN,7.674000e+10,-1.249000e+09,-8.909000e+09,-6.292400e+10,-2.062200e+10,-3.750000e+09,-2.738500e+10,6.580000e+10,6.118000e+09
msft,2022-06-30,12M,USD,1.422400e+10,-2.388600e+10,-1.813500e+10,-5.887600e+10,-3.031100e+10,8.903500e+10,2.943000e+09,...,NaN,8.903500e+10,-4.090000e+08,-2.203800e+10,-2.645600e+10,-2.388600e+10,-9.023000e+09,-3.269600e+10,4.489400e+10,7.502000e+09
msft,2023-06-30,12M,USD,1.393100e+10,-2.810700e+10,-1.980000e+10,-4.393500e+10,-2.268000e+10,8.758200e+10,-2.721000e+09,...,NaN,8.758200e+10,1.960000e+08,-1.670000e+09,-3.765100e+10,-2.810700e+10,-2.750000e+09,-2.224500e+10,4.786400e+10,9.611000e+09

In [16]:
cash_flow.columns

Index(['asOfDate', 'periodType', 'currencyCode', 'BeginningCashPosition',
       'CapitalExpenditure', 'CashDividendsPaid',
       'CashFlowFromContinuingFinancingActivities',
       'CashFlowFromContinuingInvestingActivities',
       'CashFlowFromContinuingOperatingActivities', 'ChangeInAccountPayable',
       'ChangeInCashSupplementalAsReported', 'ChangeInInventory',
       'ChangeInOtherCurrentAssets', 'ChangeInOtherCurrentLiabilities',
       'ChangeInOtherWorkingCapital', 'ChangeInPayable',
       'ChangeInPayablesAndAccruedExpense', 'ChangeInReceivables',
       'ChangeInWorkingCapital', 'ChangesInAccountReceivables',
       'ChangesInCash', 'CommonStockDividendPaid', 'CommonStockIssuance',
       'CommonStockPayments', 'DeferredIncomeTax', 'DeferredTax',
       'Depreciation', 'DepreciationAmortizationDepletion',
       'DepreciationAndAmortization', 'EffectOfExchangeRateChanges',
       'EndCashPosition', 'FinancingCashFlow', 'FreeCashFlow',
       'GainLossOnInvestmentSecurities', 'InvestingCashFlow',
       'IssuanceOfCapitalStock', 'IssuanceOfDebt', 'LongTermDebtIssuance',
       'LongTermDebtPayments', 'NetBusinessPurchaseAndSale',
       'NetCommonStockIssuance', 'NetIncome',
       'NetIncomeFromContinuingOperations', 'NetInvestmentPurchaseAndSale',
       'NetIssuancePaymentsOfDebt', 'NetLongTermDebtIssuance',
       'NetOtherFinancingCharges', 'NetOtherInvestingChanges',
       'NetPPEPurchaseAndSale', 'NetShortTermDebtIssuance',
       'OperatingCashFlow', 'OperatingGainsLosses', 'PurchaseOfBusiness',
       'PurchaseOfInvestment', 'PurchaseOfPPE', 'RepaymentOfDebt',
       'RepurchaseOfCapitalStock', 'SaleOfInvestment',
       'StockBasedCompensation'],
      dtype='object')

## Conto economico

In [17]:
aapl = Ticker('aapl')
conto_economico=aapl.income_statement()
conto_economico

,asOfDate,periodType,currencyCode,BasicAverageShares,BasicEPS,CostOfRevenue,DilutedAverageShares,DilutedEPS,DilutedNIAvailtoComStockholders,EBIT,...,ReconciledCostOfRevenue,ReconciledDepreciation,ResearchAndDevelopment,SellingGeneralAndAdministration,TaxEffectOfUnusualItems,TaxProvision,TaxRateForCalcs,TotalExpenses,TotalOperatingIncomeAsReported,TotalRevenue
symbol,,,,,,,,,,,,,,,,,,,,,
aapl,2020-09-30,12M,USD,1.735212e+10,3.31,1.695590e+11,1.752821e+10,3.28,5.741100e+10,6.996400e+10,...,1.695590e+11,1.105600e+10,1.875200e+10,1.991600e+10,0.0,9.680000e+09,0.144,2.082270e+11,6.628800e+10,2.745150e+11
aapl,2021-09-30,12M,USD,1.670127e+10,5.67,2.129810e+11,1.686492e+10,5.61,9.468000e+10,1.118520e+11,...,2.129810e+11,1.128400e+10,2.191400e+10,2.197300e+10,0.0,1.452700e+10,0.133,2.568680e+11,1.089490e+11,3.658170e+11
aapl,2022-09-30,12M,USD,1.621596e+10,6.15,2.235460e+11,1.632582e+10,6.11,9.980300e+10,1.220340e+11,...,2.235460e+11,1.110400e+10,2.625100e+10,2.509400e+10,0.0,1.930000e+10,0.162,2.748910e+11,1.194370e+11,3.943280e+11
aapl,2023-09-30,12M,USD,NaN,NaN,2.141370e+11,NaN,NaN,9.699500e+10,1.176690e+11,...,2.141370e+11,1.151900e+10,2.991500e+10,2.493200e+10,0.0,1.674100e+10,0.147,2.689840e+11,1.143010e+11,3.832850e+11
aapl,2023-09-30,TTM,USD,1.574423e+10,6.16,2.141370e+11,1.581255e+10,6.13,9.699500e+10,1.176690e+11,...,2.141370e+11,1.151900e+10,2.991500e+10,2.493200e+10,0.0,1.674100e+10,0.147,2.689840e+11,1.143010e+11,3.832850e+11

In [18]:
conto_economico.columns

Index(['asOfDate', 'periodType', 'currencyCode', 'BasicAverageShares',
       'BasicEPS', 'CostOfRevenue', 'DilutedAverageShares', 'DilutedEPS',
       'DilutedNIAvailtoComStockholders', 'EBIT', 'EBITDA', 'GrossProfit',
       'InterestExpense', 'InterestExpenseNonOperating', 'InterestIncome',
       'InterestIncomeNonOperating', 'NetIncome',
       'NetIncomeCommonStockholders', 'NetIncomeContinuousOperations',
       'NetIncomeFromContinuingAndDiscontinuedOperation',
       'NetIncomeFromContinuingOperationNetMinorityInterest',
       'NetIncomeIncludingNoncontrollingInterests', 'NetInterestIncome',
       'NetNonOperatingInterestIncomeExpense', 'NormalizedEBITDA',
       'NormalizedIncome', 'OperatingExpense', 'OperatingIncome',
       'OperatingRevenue', 'OtherIncomeExpense',
       'OtherNonOperatingIncomeExpenses', 'PretaxIncome',
       'ReconciledCostOfRevenue', 'ReconciledDepreciation',
       'ResearchAndDevelopment', 'SellingGeneralAndAdministration',
       'TaxEffectOfUnusualItems', 'TaxProvision', 'TaxRateForCalcs',
       'TotalExpenses', 'TotalOperatingIncomeAsReported', 'TotalRevenue'],
      dtype='object')

## Misure di valutazione

Note:
Trailing 12 months (TTM) è il termine per i dati degli ultimi 12 mesi consecutivi utilizzati per riportare i dati finanziari.
I 12 mesi finali di una società rappresentano la sua performance finanziaria per un periodo di 12 mesi; in genere non rappresenta un periodo di fine anno fiscale.

In [19]:
aapl = Ticker('msft')
misure_valutazione=aapl.valuation_measures.reset_index().set_index('asOfDate')
misure_valutazione

,symbol,periodType,EnterpriseValue,EnterprisesValueEBITDARatio,EnterprisesValueRevenueRatio,ForwardPeRatio,MarketCap,PbRatio,PeRatio,PegRatio,PsRatio
asOfDate,,,,,,,,,,,
2022-09-02,msft,TTM,1.866189e+12,NaN,NaN,25.3807,1.909668e+12,11.466584,26.534715,1.9007,9.737693
2022-09-05,msft,TTM,NaN,18.617392,9.412361,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-31,msft,3M,1.740770e+12,71.118591,33.002251,25.1889,1.787732e+12,10.289685,25.814855,2.1209,8.880101
2023-03-31,msft,3M,2.104706e+12,78.774837,39.818872,26.6667,2.144087e+12,11.707622,32.033333,2.1666,10.592970
2023-06-30,msft,3M,2.486996e+12,85.513746,44.261266,30.8642,2.530893e+12,13.000073,36.894908,2.5078,12.272931
2023-09-30,msft,3M,2.294425e+12,72.310917,40.597084,28.6533,2.345716e+12,11.374660,32.618802,2.3316,11.133162
2024-01-12,msft,TTM,2.828255e+12,NaN,NaN,35.2113,2.887211e+12,13.081232,37.642442,2.3509,13.285759
2024-01-15,msft,TTM,NaN,25.250473,12.955224,NaN,NaN,NaN,NaN,NaN,NaN

### MarketCap più recente

In [20]:
misure_valutazione.loc[(misure_valutazione['periodType']=='TTM') & (misure_valutazione['MarketCap'].notna())].max()['MarketCap']
#Prendere il date più recente

2887210946946.0

### PeRatio

In [21]:
misure_valutazione.loc[(misure_valutazione['periodType']=='TTM') & (misure_valutazione['PeRatio'].notna())].max()['PeRatio']

37.642442

### PeRatio fordward

In [22]:
misure_valutazione.loc[(misure_valutazione['periodType']=='TTM') & (misure_valutazione['ForwardPeRatio'].notna())].max()['ForwardPeRatio']

35.2113

### Beta

Indica la volatilità dello stock, più alto + volatile

In [23]:
aapl = Ticker('msft')
aapl.summary_detail['msft']['beta']

TypeError: string indices must be integers

In [55]:
misure_valutazione.columns

Index(['asOfDate', 'periodType', 'EnterpriseValue',
       'EnterprisesValueEBITDARatio', 'EnterprisesValueRevenueRatio',
       'ForwardPeRatio', 'MarketCap', 'PbRatio', 'PeRatio', 'PegRatio',
       'PsRatio'],
      dtype='object')

### Seleziono i più interessanti

In [24]:
aapl = Ticker('aapl')
types = ['TotalDebt', 'TotalAssets', 'EBIT', 'EBITDA', 'PeRatio', 'EnterpriseValue','']
aapl.get_financial_data(types, trailing=False)

,asOfDate,periodType,currencyCode,EBIT,EBITDA,TotalAssets,TotalDebt
symbol,,,,,,,
aapl,2020-09-30,12M,USD,6.996400e+10,8.102000e+10,3.238880e+11,1.124360e+11
aapl,2021-09-30,12M,USD,1.118520e+11,1.231360e+11,3.510020e+11,1.247190e+11
aapl,2022-09-30,12M,USD,1.220340e+11,1.331380e+11,3.527550e+11,1.200690e+11
aapl,2023-09-30,12M,USD,1.176690e+11,1.291880e+11,3.525830e+11,1.110880e+11

In [25]:
Ticker('aapl').financial_data

{'aapl': 'Invalid Cookie'}